### ISSUE TITLE
Compiler warnings and errors on the swift-concurrency branch

### ISSUE THREAD

**Issue by AustinConlon** [apple/cloudkit-sample-privatedb#2]
> 'async(priority:operation:)' is deprecated: `async` was replaced by `Task.init` and will be removed shortly.

> Missing argument for parameter 'deleting' in call

<img width="1512" alt="Screen Shot 2021-09-19 at 4 20 18 PM" src="https://user-images.githubusercontent.com/1305957/133946144-f7190a5f-8d18-44ac-ba46-c3b2cfbf0414.png">

**Comment by sjrmanning** [comment]
This branch has been updated, please try it out! Thanks.
